version: '4.0'
services:
  shopping-task-management:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/task_management
      - PORT=8000
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
